### ISSUE TITLE
[New Feature]: Today Tab

### ISSUE THREAD

**Issue by TheSeagullDev** [Ejenda/Ejenda#101]

**Comment by TheSeagullDev** [comment]
IT ONLY TOOK 
![image](https://github.com/user-attachments/assets/8d0a3e4a-ce16-41ee-8f2c-7af27cbe229d)

**Comment by GrahamSH-LLK** [comment]
> IT ONLY TOOK ![image](https://private-user-images.githubusercontent.com/67653706/354915273-8d0a3e4a-ce16-41ee-8f2c-7af27cbe229d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTUxNTAsIm5iZiI6MTcyMjc5NDg1MCwicGF0aCI6Ii82NzY1MzcwNi8zNTQ5MTUyNzMtOGQwYTNlNGEtY2UxNi00MWVlLThmMmMtN2FmMjdjYmUyMjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE4MDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NWVkN2MyYjVhMjBjNWEwNTRkOWM2YTYwYjg3NDYxZjVhODgwYTlhZDRlNDI4MjI0MzVlN2RkNTgyMjQxZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mj-rniPNb4bMWB-6YbCUbsHsQw_0bq9u7hF3Y9SvIBo)

Oh I didn’t actually do it yet I just closed it
