### ISSUE TITLE
FAQ is off center

### ISSUE THREAD

**Issue by Thingyman-DEV** [Ejenda/Ejenda#62]
### What happened?

The FAQ text is slightly too high on the button.
![image](https://user-images.githubusercontent.com/67653706/133802880-920a49ae-b596-45df-bbaa-dc753f38d901.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by GrahamSH-LLK** [comment]
Uhh, I deleted the FAQ button?

**Comment by Thingyman-DEV** [comment]
Guess the update wasn't showing for me, it is now
