### ISSUE TITLE
[Feature request]: Instead of `graham@ejenda.org` use `support@ejenda.org` 

### ISSUE THREAD

**Issue by Explosion-Scratch** [Ejenda/Ejenda#65]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

[To be clear I did not search for existing issues, I spent that time typing this comment]

I'm always frustrated when [people use their personal emails instead of creating cool looking ones because they have a domain already]

### Describe the solution you'd like

Use `support@ejenda.org` as the email address in settings

### Anything else?

_nope_

**Comment by Thingyman-DEV** [comment]
Will talk to graham about this

**Comment by GrahamSH-LLK** [comment]
support@ejenda.org exists?
